
var aboutUs = function() {
	return [
	 '<div id="aboutContent">',
      '<div class="topBanner">',
        '<div class="bannerBg">',
          '<img src="images/top_bg.png" alt="">',
        '</div>',
        '<div class="bannerText">',
          '<div>',
            '<div class="bannerTextBox">',
              '<span class="i18n" i18n-text="aboutBannerText01"></span>',
              '<span class="i18n" i18n-text="aboutBannerText02"></span>',
            '</div>',
          '</div>',
        '</div>',
      '</div>',
      '<div class="aboutMain">',
        '<div class="aboutMainContent">',
          '<div class="itemText">',
            '<h3 class="i18n" i18n-text="aboutUtravelTitle01"></h3>',
            '<p class="i18n" i18n-text="utravelIntroText01"></p>',
          '</div>',
          '<div class="itemText">',
            '<h3 class="i18n" i18n-text="aboutUtravelTitle02"></h3>',
            '<p class="i18n" i18n-text="utravelIntroText02"></p>',
          '</div>',
          '<div class="itemText">',
            '<h3 class="i18n" i18n-text="aboutUtravelTitle03"></h3>',
            '<p class="i18n" i18n-text="utravelIntroText03"></p>',
          '</div>',
          '<div class="itemText">',
            '<h3 class="i18n" i18n-text="aboutUtravelTitle04"></h3>',
            '<p class="i18n" i18n-text="utravelIntroText04"></p>',
          '</div>',
          '<div class="itemText">',
            '<h3 class="i18n" i18n-text="aboutUtravelTitle05"></h3>',
            '<p class="i18n" i18n-text="utravelIntroText05"></p>',
          '</div>',
        '</div>',
        '<div class="contactUs">',
          '<div class="contactBg">',
            '<img class="lazy" data-original="images/bottom_bg.png" alt="">',
          '</div>',
          '<div class="contactBox">',
            '<div>',
              '<div class="contactBoxText">',
                '<div class="textBox">',
                  '<h3 class="i18n" i18n-text="aboutContactUs"></h3>',
                  '<div class="contactType">',
                    '<div class="itemContactType">',
                      '<div class="left">',
                        '<span class="i18n" i18n-text="serviceHot"></span>',
                        '<p>400-077-8755</p>',
                      '</div>',
                      '<div class="left">',
                        '<span class="i18n" i18n-text="companyEmail"></span>',
                        '<p>kefuzhongxin@bcwcar.com</p>',
                      '</div>',
                    '</div>',
                    '<div class="itemContactType">',
                      '<div class="left">',
                        '<span class="i18n" i18n-text="officalWx"></span>',
                        '<p>Ulvjia</p>',
                      '</div>',
                      '<div class="left">',
                        '<span class="i18n" i18n-text="officalQQ"></span>',
                        '<p>3386339106</p>',
                      '</div>',
                    '</div>',
                  '</div>',
                '</div>',
              '</div>',
            '</div>',
          '</div>',
        '</div>',
      '</div>',
    '</div>',
	].join('')
}